spring:
  datasource:
    url: jdbc:mysql://localhost:3306/G55_TODO_DB?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Europe/Berlin
    username: root
    password: root
    tomcat:
      test-while-idle: true
      validation-query: SELECT 1
      initial-size: 15
      max-wait: 20000
      max-active: 50
      max-idle: 15
      min-idle: 8
      default-auto-commit: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
